apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: rifqio/auth-service-ticket
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rifqio/ticket-service-ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rifqio/ticket-client-next
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/app/**/*.js'
            dest: .
  