apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-auth-api
  template:
    metadata:
      labels:
        app: ticket-auth-api
    spec: 
      containers:
      - name: ticket-auth-api
        image: rifqio/auth-service-ticket
        env:
          - name: JWT_SECRET
            value: "29727dd2e90e14090690e4d60c89eb70"
          - name: MONGO_URL
            value: mongodb://auth-api-mongodb:27017/auth
          - name: APP_PORT
            value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-auth-api
spec:
  selector:
    app: ticket-auth-api
  ports:
  - port: 4000
    targetPort: 4000

