apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-order-api
  template:
    metadata:
      labels:
        app: ticket-order-api
    spec: 
      containers:
      - name: ticket-order-api
        image: rifqio/order-service-ticket
        env:
          - name: NODE_ENV
            value: development
          - name: APP_NAME
            value: "Order-Service"
          - name: JWT_SECRET
            value: "29727dd2e90e14090690e4d60c89eb70"
          - name: MONGO_URL
            value: mongodb://order-api-mongodb:27017/order
          - name: APP_PORT
            value: "5500"
          - name: NATS_HOST
            value: http://ticket-nats-srv:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
            
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-order-api
spec:
  selector:
    app: ticket-order-api
  ports:
  - port: 5500
    targetPort: 5500

