apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-ticket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-ticket-api
  template:
    metadata:
      labels:
        app: ticket-ticket-api
    spec: 
      containers:
      - name: ticket-ticket-api
        image: rifqio/ticket-service-ticket
        env:
          - name: NODE_ENV
            value: development
          - name: APP_NAME
            value: "Ticket-Service"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_SECRET
          - name: MONGO_URL
            value: mongodb://ticket-api-mongodb:27017/auth
          - name: APP_PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-ticket-api
spec:
  selector:
    app: ticket-ticket-api
  ports:
  - port: 5000
    targetPort: 5000

